### ISSUE TITLE
Pre-release automations

### ISSUE THREAD

**Issue by ianjoshi** [remla25-team6/operation#1]
Ensure **pre-release workflows** for all repositories achieve the following:
- Automatic increase of Patch versions, bumps to minor or major versions can remain manual.
- After a stable release, main is set to a pre-release version that is higher than the latest release.
- The automation supports to release multiple versions of the same pre-release, like 1.2.3-pre-ăną ,
in which n is an automatically set counter or date.

**Comment by MaartenVladimir** [comment]
Possibly a good idea to exclude pushes to main with tags as follows:
```yml
on:
  push:
      branches:
        - main
      tags-ignore:
        - '*'
```
This results in seperate workflows for manual releases (pushed tags to main) or automatic releases (commits to main _without_ any tag)
